//ZTPJ I2 14 LAB07
//Artur Ziemba
//za32917@zut.edu.pl


package mvc.model.webService.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "webServiceC", targetNamespace = "http://webService.model.mvc/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceC {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersons", targetNamespace = "http://webService.model.mvc/", className = "mvc.model.webService.GetPersons")
    @ResponseWrapper(localName = "getPersonsResponse", targetNamespace = "http://webService.model.mvc/", className = "mvc.model.webService.GetPersonsResponse")
    @Action(input = "http://webService.model.mvc/webServiceC/getPersonsRequest", output = "http://webService.model.mvc/webServiceC/getPersonsResponse")
    public String getPersons(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
