//ZTPJ I2 14 LAB07
//Artur Ziemba
//za32917@zut.edu.pl


package mvc.model.webService.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "webServiceCService", targetNamespace = "http://webService.model.mvc/", wsdlLocation = "http://localhost:8095/webServiceC?wsdl")
public class WebServiceCService
    extends Service
{

    private final static URL WEBSERVICECSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICECSERVICE_EXCEPTION;
    private final static QName WEBSERVICECSERVICE_QNAME = new QName("http://webService.model.mvc/", "webServiceCService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8095/webServiceC?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICECSERVICE_WSDL_LOCATION = url;
        WEBSERVICECSERVICE_EXCEPTION = e;
    }

    public WebServiceCService() {
        super(__getWsdlLocation(), WEBSERVICECSERVICE_QNAME);
    }

    public WebServiceCService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICECSERVICE_QNAME, features);
    }

    public WebServiceCService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICECSERVICE_QNAME);
    }

    public WebServiceCService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICECSERVICE_QNAME, features);
    }

    public WebServiceCService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceCService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceC
     */
    @WebEndpoint(name = "webServiceCPort")
    public WebServiceC getWebServiceCPort() {
        return super.getPort(new QName("http://webService.model.mvc/", "webServiceCPort"), WebServiceC.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceC
     */
    @WebEndpoint(name = "webServiceCPort")
    public WebServiceC getWebServiceCPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webService.model.mvc/", "webServiceCPort"), WebServiceC.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICECSERVICE_EXCEPTION!= null) {
            throw WEBSERVICECSERVICE_EXCEPTION;
        }
        return WEBSERVICECSERVICE_WSDL_LOCATION;
    }

}
